### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by jbrisbin** [reactive-ipc/reactive-ipc-jvm#4]
I'm second-guessing the submodule naming. Maybe it should be:

```
ripc-core
ripc-protocol-tcp
ripc-transport-netty4
ripc-composition-rxjava1
```

Rather than the longer `reactive-ipc-*`.

**Comment by benjchristensen** [comment]
I find the `ripc` naming easier for the modules and artifacts. I like Reactive IPC as the broader naming, but `ripc` as the short-form for this type of stuff.

**Comment by jbrisbin** [comment]
Modules have been renamed.
